name: 'State Machine'
on:
  pull_request_target:
    types:
      - assigned
      - assigned
      - unassigned
      - labeled
      - unlabeled
      - opened
      - edited
      - closed
      - reopened
      - synchronize
      - ready_for_review
      - locked
      - unlocked
      - review_requested
      - review_request_removed
jobs:
  machine:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello world"
      #
      - uses: JuliaLang/pull-request-state-machine@main
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
